version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node:8
    working_directory: ~/app
jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install package
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: eslint
          command: npm run eslint
      - run:
          name: test
          command: npm run test